bhaile/bhaile/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    # Class based views handles logic
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'),
        name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    # redirect to properties page
    path('', include('properties.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bhaile/properties/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    SearchResultListView,
    BookingListView,
    BookingDetailView,
    BookingUpdateView,
    BookingDeleteView,

)

urlpatterns = [
    # to access the home page from views
    # url path mapped to home function in views
    path('', PostListView.as_view(), name='properties-home'),
    path('bookings/', BookingListView.as_view(template_name='properties/bookings.html'), name='booking'),
    path('bookings/<int:pk>/', BookingDetailView.as_view(), name='booking-detail'),
    path('bookings/<int:pk>/update', BookingUpdateView.as_view(), name='booking-update'),
    path('bookings/<int:pk>/delete', BookingDeleteView.as_view(), name='booking-delete'),
    #
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    # detail view for the properties
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<category>/', PostDetailView.as_view(), name='post-detail'),
    # shares template with update view
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='properties-about'),
    path('search/', SearchResultListView.as_view(), name='properties-search'),
]

bhaile/properties/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # set date posted to timezone
    date_posted = models.DateTimeField(default=timezone.now)
    # if user is deleted, delete their posts
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    ACCOMMODATION_CATEGORIES = (
        ('TWN', 'Twin'),
        ('SIN', 'Single'),
        ('DOB', 'Double'),
        ('SIN-EN', 'Single EnSuite'),
        ('DOB-EN', 'Double EnSuite'),
        ('HSE', 'Whole House')
    )
    category = models.CharField(max_length=6, choices=ACCOMMODATION_CATEGORIES, null=True)
    capacity = models.IntegerField(null=True)

    # magic method
    def __str__(self):
        return self.title

    def get_accommodation_category(self):
        accommodation_categories = dict(self.ACCOMMODATION_CATEGORIES)
        accommodation_category = accommodation_categories.get(self.category)
        return accommodation_category

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Booking(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_booked = models.DateTimeField(default=timezone.now)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    accommodation = models.ForeignKey(Post, on_delete=models.CASCADE)
    move_in = models.DateTimeField()
    move_out = models.DateTimeField()

    def __str__(self):
        return f'{self.author} has booked {self.accommodation} from {self.move_in} to {self.move_out}'

    def get_accommodation_category(self):
        accommodation_categories = dict(self.accommodation.ACCOMMODATION_CATEGORIES)
        accommodation_category = accommodation_categories.get(self.accommodation.category)
        return accommodation_category

    def get_absolute_url(self):
        return reverse('booking-detail', kwargs={'pk': self.pk})

bhaile/properties/forms.py
from django import forms


class AvailabilityForm(forms.Form):
    move_in = forms.DateTimeField(
        required=True,
        input_formats=['%d/%m/%Y %H:%M', ]
    )
    move_out = forms.DateTimeField(
        required=True,
        input_formats=['%d/%m/%Y %H:%M', ]
    )

bhaile/properties/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    View,
)
from django.db.models import Q
from .models import Post, Booking
from .forms import AvailabilityForm
from properties.booking_functions.availability import check_availability
from django.urls import reverse, reverse_lazy


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'properties/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'properties/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class BookingListView(ListView):
    model = Booking
    ordering = ['-date_booked']
    paginate_by = 5

    # implement logic that only show bookings for the author of the booking
    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            bookings = Booking.objects.all().order_by('-date_booked')
            return bookings
        else:
            bookings = Booking.objects.filter(author=self.request.user).order_by('-date_booked')
            return bookings


class BookingDetailView(DetailView):
    model = Booking


# displays all posts from a user
class UserPostListView(ListView):
    model = Post
    template_name = 'properties/user_posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    # template_name = 'properties/post_detail.html'

    # display detail page
    def get(self, request, *args, **kwargs):
        # category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        # accommodation_list = Post.objects.filter(category=category)
        post = self.kwargs['pk']
        accommodation_list = Post.objects.filter(id=post)

        if len(accommodation_list) > 0:
            accommodation = accommodation_list[0]
            accommodation_category = dict(accommodation.ACCOMMODATION_CATEGORIES).get(accommodation.category, None)
            accommodation_id = accommodation.id
            accommodation_author = accommodation.author
            accommodation_title = accommodation.title
            accommodation_content = accommodation.content
            accommodation_capacity = accommodation.capacity
            accommodation_date_posted = accommodation.date_posted
            context = {
                'accommodation_id': accommodation_id,
                'accommodation_author': accommodation_author,
                'accommodation_date_posted': accommodation_date_posted,
                'accommodation_title': accommodation_title,
                'accommodation_content': accommodation_content,
                'accommodation_capacity': accommodation_capacity,
                'accommodation_category': accommodation_category,
                'form': form,
            }
            return render(request, 'properties/post_detail.html', context)
        else:
            return HttpResponse('Accommodation does not exist')

    # make booking
    def post(self, request, *args, **kwargs):
        # category = self.kwargs.get('category', None)
        # accommodation_list = Post.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        post = self.kwargs['pk']
        accommodation_list = Post.objects.filter(id=post)

        data = None

        if form.is_valid():
            data = form.cleaned_data

        available_accommodation = []
        for accommodation in accommodation_list:
            if check_availability(accommodation, data['move_in'], data['move_out']):
                available_accommodation.append(accommodation)

        if len(available_accommodation) > 0:
            accommodation = available_accommodation[0]
            booking = Booking.objects.create(
                author=self.request.user,
                accommodation=accommodation,
                move_in=data['move_in'],
                move_out=data['move_out']
            )
            booking.save()
            messages.success(request, f'Booking Successful')
            return redirect('booking')
        else:
            messages.error(request, f'Please correct the error below')
            return HttpResponse(f'This accommodation is booked!'
                                'Please try booking an alternate date or alternate accommodation')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'category', 'capacity']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'category', 'capacity']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # only authors of the post can update it
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# Booking
class BookingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Booking
    fields = ['accommodation', 'move_in', 'move_out']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # only authors of the post can update it
    def test_func(self):
        booking = self.get_object()
        if self.request.user == booking.author:
            return True
        return False


class BookingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Booking
    # redirect to home page once a post has been deleted
    success_url = reverse_lazy('booking')

    # only authors of the post can delete it
    def test_func(self):
        booking = self.get_object()
        if self.request.user == booking.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    # redirect to home page once a post has been deleted
    success_url = '/'

    # only authors of the post can delete it
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# displays all search results
class SearchResultListView(ListView):
    model = Post
    template_name = 'properties/search_results.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6

    # searching for all fields in the Post model
    # Used a get request since it doesnt affect the state of the app
    # nothing in the database is changing
    def get_queryset(self, **kwargs):
        query = self.request.GET.get('q')
        if not query:
            query = ''
        results = Post.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(date_posted__icontains=query) |
            Q(author__username__icontains=query)
        )
        return results


def about(request):
    return render(request, 'properties/about.html', {'title': 'About'})

bhaile/properties/templates/properties/about.html
{% extends 'properties/base.html' %}
{% block content %}
    <h1>About!</h1>
{% endblock content %}

bhaile/properties/templates/properties/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'properties/main.css' %}">

    {% if title %}
        <title>Properties - {{ title }}</title>
    {% else %}
        <title>Properties</title>
    {% endif %}
</head>

<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Bhaile</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <!---Instead of hardcoding use url route-->
                    <a class="nav-item nav-link" href="{% url 'properties-about' %}">About</a>
                </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <!---Show logout when user is logged in-->
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'post-create' %}">New Property</a>
                        <a class="nav-item nav-link" href="{% url 'booking' %}">Bookings</a>

                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                User Info
                            </a>
                            <div class="dropdown-menu">
                                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>

                        <form class="form-inline my-2 my-lg-0" action="{% url 'properties-search' %}" method="GET">
                            {% csrf_token %}
                            <input name ="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                            <button class="btn btn-outline-info my-2 my-sm-0 btn-sm" type="submit">Search</button>
                        </form>

                    {% else %}
                        <!---Instead of hardcoding use url route-->
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>
</header>

<!--Sidebar--->
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>


        {% if user.is_authenticated %}

        <div class="col-md-4">
            <div class="content-section">
                <h3>Hello, {{ user.username }}</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Account</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
                <form class="form-inline my-2 my-lg-0" action="{% url 'properties-search' %}" method="GET">
                    {% csrf_token %}
                    <input name ="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                    <button class="btn btn-outline-info my-2 my-sm-0 btn-sm" type="submit">Search</button>
                </form>
            </div>
        </div>
        {% else %}
            <div class="col-md-4">
            <div class="content-section">
                <h3>Sidebar</h3>
                <p class='text-muted'>Please make an account for full access to our features
                </p>
            </div>
        </div>
        {% endif %}

    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>

</body>
</html>

bhaile/properties/templates/properties/book.html
{% extends 'properties/base.html' %}
{% block content %}

    <form class="form-inline my-2 my-lg-0" action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button class="btn btn-outline-info my-2 my-sm-0 btn-sm" type="submit">Book Accommodation</button>
    </form>

    <div class="pagination">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% endblock content %}

bhaile/properties/templates/properties/booking_confirm_delete.html
{% extends 'properties/base.html' %}
<!---Use crispy for styling--->
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <!----csrf protects form against attacks------>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Booking</legend>
                <h3>Are you sure you want to delete the booking:</h3>
                <h3>Title: {{ object.accommodation }}</h3>
                <h3>Type: {{ object.get_accommodation_category }} </h3>
                <h3>From {{ object.move_in}} to {{ object.move_out }}</h3>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'booking-detail' object.id %}" >Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

bhaile/properties/templates/properties/booking_detail.html
{% extends 'properties/base.html' %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src=" {{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="mt-4 mb-2 article-metadata">
                <a class="mr-2" href="{% url 'profile' %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.move_in|date:"F d, Y" }} - {{ object.move_out|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <div class="text-right">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'booking-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'booking-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h4 class="article-title" >{{ object.accommodation }}</h4>
            <p class="article-content">{{ object.get_accommodation_category }} for {{ object.accommodation.capacity }} person/s</p>
            <p class="article-content">Dates booked: {{ object.move_in|date:"F d, Y" }} - {{ object.move_out|date:"F d, Y" }}</p>
        </div>
    </article>
{% endblock content %}

bhaile/properties/templates/properties/booking_form.html
{% extends 'properties/base.html' %}
<!---Use crispy for styling--->
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <!----csrf protects form against attacks------>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Booking</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Book</button>
            </div>
        </form>
    </div>
{% endblock content %}

bhaile/properties/templates/properties/bookings.html
{% extends 'properties/base.html' %}
{% block content %}
    <h1 class="mb-3 page-title">Bookings for {{ user.username}}</h1>
    {% for booking in booking_list %}
        <article class="media content-section">
            <a href="{% url 'profile'  %}">
                <img class="rounded-circle article-img" src=" {{ booking.author.profile.image.url }}">
            </a>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'profile'  %}">{{ booking.author }}</a>
                    <small class="text-muted">{{ booking.date_booked|date:"F d, Y: P" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'booking-detail' booking.id %}">{{ booking.accommodation }}</a></h2>
                <small class="article-content text-muted">{{ booking.move_in|date:"F d, Y" }} - {{ booking.move_out|date:"F d, Y" }}</small>
                <p class="article-content">{{ booking.get_accommodation_category }} for {{ booking.accommodation.capacity }} person/s</p>

            </div>
        </article>
    {% endfor %}

    <div class="pagination">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% endblock content %}

bhaile/properties/templates/properties/home.html
{% extends 'properties/base.html' %}
{% block content %}
    <h1 class="page-title">Properties</h1>

    {% for post in posts %}
        <article class="media content-section">
            <a href="{% url 'profile'  %}">
                <img class="rounded-circle article-img" src=" {{ post.author.profile.image.url }}">
            </a>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y: P" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.get_accommodation_category }}</p>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    <div class="pagination">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class= "btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% endblock content %}

bhaile/properties/templates/properties/post_confirm_delete.html
{% extends 'properties/base.html' %}
<!---Use crispy for styling--->
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <!----csrf protects form against attacks------>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the property "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}" >Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

bhaile/properties/templates/properties/post_detail.html
{% extends 'properties/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src=" {{ accommodation_author.profile.image.url }}">
        <div class="media-body">
            <div class="mt-4 mb-2 article-metadata">
                <a class="mr-2" href="{% url 'profile' %}">{{ accommodation_author }}</a>
                <small class="text-muted">{{ accommodation_date_posted|date:"F d, Y: P" }} </small>
                {% if accommodation_author == user %}
                    <div class="text-right">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' accommodation_id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' accommodation_id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2><a class="article-title">{{ accommodation_title }}</a></h2>
            <h3 class="article-content">Property Details: </h3>
            <p class="article-content">  {{ accommodation_category }}</p>
            <p class="article-content">  {{ accommodation_content }}</p>
            <h3 class="article-content">Capacity: </h3>
            <p class="article-content">  {{ accommodation_capacity }}</p>

            <form class="form-inline my-2 my-lg-0" action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-outline-info my-2 my-sm-0 btn-sm" type="submit">Book Accommodation</button>
            </form>
        </div>
    </article>

{% endblock content %}

bhaile/properties/templates/properties/post_form.html
{% extends 'properties/base.html' %}
<!---Use crispy for styling--->
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <!----csrf protects form against attacks------>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Property Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}